//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYH.WorkOrder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LYH.WorkOrder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;A保存 的本地化字符串。
        /// </summary>
        internal static string A保存 {
            get {
                return ResourceManager.GetString("A保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;A新增 的本地化字符串。
        /// </summary>
        internal static string A新增 {
            get {
                return ResourceManager.GetString("A新增", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;C取消 的本地化字符串。
        /// </summary>
        internal static string C取消 {
            get {
                return ResourceManager.GetString("C取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;C退出 的本地化字符串。
        /// </summary>
        internal static string C退出 {
            get {
                return ResourceManager.GetString("C退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光 的本地化字符串。
        /// </summary>
        internal static string G激光 {
            get {
                return ResourceManager.GetString("G激光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H1 的本地化字符串。
        /// </summary>
        internal static string HJ_H1 {
            get {
                return ResourceManager.GetString("HJ_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 焊接 的本地化字符串。
        /// </summary>
        internal static string H焊接 {
            get {
                return ResourceManager.GetString("H焊接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是数字，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string IsNotNumber {
            get {
                return ResourceManager.GetString("IsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G 的本地化字符串。
        /// </summary>
        internal static string JG_G {
            get {
                return ResourceManager.GetString("JG_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C15 的本地化字符串。
        /// </summary>
        internal static string JJ_C15 {
            get {
                return ResourceManager.GetString("JJ_C15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string J警告 {
            get {
                return ResourceManager.GetString("J警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普冲 的本地化字符串。
        /// </summary>
        internal static string P普冲 {
            get {
                return ResourceManager.GetString("P普冲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        internal static string SC_S {
            get {
                return ResourceManager.GetString("SC_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction was rollbacked or commited, please provide an open transaction. 的本地化字符串。
        /// </summary>
        internal static string SqlHelper_Execute_transaction_showtip {
            get {
                return ResourceManager.GetString("SqlHelper_Execute_transaction_showtip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon System {
            get {
                object obj = ResourceManager.GetObject("System", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 数冲 的本地化字符串。
        /// </summary>
        internal static string S数冲 {
            get {
                return ResourceManager.GetString("S数冲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string T提示 {
            get {
                return ResourceManager.GetString("T提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 admin 的本地化字符串。
        /// </summary>
        internal static string UT_Admin {
            get {
                return ResourceManager.GetString("UT_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string UT_Audit {
            get {
                return ResourceManager.GetString("UT_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核对 的本地化字符串。
        /// </summary>
        internal static string UT_Check {
            get {
                return ResourceManager.GetString("UT_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CNC统计 的本地化字符串。
        /// </summary>
        internal static string UT_CNCInput {
            get {
                return ResourceManager.GetString("UT_CNCInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入 的本地化字符串。
        /// </summary>
        internal static string UT_Input {
            get {
                return ResourceManager.GetString("UT_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折弯 的本地化字符串。
        /// </summary>
        internal static string W折弯 {
            get {
                return ResourceManager.GetString("W折弯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;X保存 的本地化字符串。
        /// </summary>
        internal static string X保存 {
            get {
                return ResourceManager.GetString("X保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;X修改 的本地化字符串。
        /// </summary>
        internal static string X修改 {
            get {
                return ResourceManager.GetString("X修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压段差 的本地化字符串。
        /// </summary>
        internal static string Y压段差 {
            get {
                return ResourceManager.GetString("Y压段差", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z1 的本地化字符串。
        /// </summary>
        internal static string ZP_Z1 {
            get {
                return ResourceManager.GetString("ZP_Z1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入仓 的本地化字符串。
        /// </summary>
        internal static string Z入仓 {
            get {
                return ResourceManager.GetString("Z入仓", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装配 的本地化字符串。
        /// </summary>
        internal static string Z装配 {
            get {
                return ResourceManager.GetString("Z装配", resourceCulture);
            }
        }
    }
}
